### ISSUE TITLE
12.17.x support

### ISSUE THREAD

**Issue by jaymarvels** [Epicweb-Optimizely/Epicweb.Optimizely.QuickNavExtension#1]
Have tried using both:

```        //add links in a simple way in startup.
        services
            .AddQuickNav(QuickNavigator.FIND)
            .AddQuickNav(QuickNavigator.Admin)
            .AddQuickNav(QuickNavigator.ContentType)
            .AddQuickNav(QuickNavigator.LogOut);
```
And

` "Epicweb.QuickNav": "find,admin,contenttype,logout",`

In my solution and both do not render anything on page. No errors in console.

**Comment by LucGosso** [comment]
Hi Jacob, Seems that you are missing @await Html.RenderEPiServerQuickNavigatorAsync() in top body, dont you see the Optimizely blue tab at all?

**Comment by jaymarvels** [comment]
Hi @LucGosso  you're right, I was missing the await, it wasn't so obvious. 

I remember back in the Epi 7-11 days that this had an option to do directly from the rendered page to the page in the cms to start editing, there isn't one of your const strings thats built in to handle this, is there a way to get this feature back?

Edit: Don't worry, its there, I am just blind.
